Default: &defaults
  database: test1.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: test1_test.sqlite3
  <<: *defaults

Staging:
  database: test1_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: test1_production.sqlite3
  poolsize: 100
  <<: *defaults
